name: Caseflow Web
on:
  workflow_dispatch:
    inputs:
      ecr:
        required: true
      version:
        required: true
      reponame:
        required: true
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./app/caseflow_web/package-lock.json"
    - run: npm install --force
      working-directory: ./app/caseflow_web
    - run: CI=false npm run build
      working-directory: ./app/caseflow_web

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./app/caseflow_web
        push: true
        tags: ${{ github.event.inputs.ecr }}/${{ github.event.inputs.reponame }}:${{ github.event.inputs.version }}
    
    - name: Download ECS Task Definition JSON file from S3
      run: |
            aws s3 cp s3://caseflow-secrets/caseflow_web-revision148.json ./ecs-task-definition/caseflow_web-revision148.json \
              --region ca-central-1
        
      shell: /usr/bin/bash -e {0}
      env:
          AWS_DEFAULT_REGION: ca-central-1
          AWS_REGION: ca-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./ecs-task-definition/caseflow_web-revision148.json
        container-name: caseflow_web
        image: ${{ github.event.inputs.ecr }}/${{ github.event.inputs.reponame }}:${{ github.event.inputs.version }}
    
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: caseflow_web
        cluster: caseflow
        wait-for-service-stability: true
